// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Kitten_Roulette_Project

#include "ui.h"

void InitGUI()
{

}

void AutoUpdate()
{

}

void Main_OnLoaded(lv_event_t * e)
{
    // Your code here
}
